### ISSUE TITLE
Replace non-CSS style hacks with proper CSS

### ISSUE THREAD

**Issue by krishmaj** [DUNE/dunedb#9]

**Comment by micchickenburger** [comment]
Reference pull request #8 review discussion:  https://github.com/DUNE/dunedb/pull/8#discussion_r760480075_

**Comment by krishmaj** [comment]
@micchickenburger Would replacing the `pre #{''}` elements with appropriate numbers of `br` elements be satisfactory?  And was there anything else that you noticed needed replacing?

**Comment by micchickenburger** [comment]
`br` elements are also hacks for using HTML to affect presentation.  The appropriate solution is CSS.

What do all of the elements have in common that extra space is needed?  Do they all have the same element after them?  If so, you can target that element in CSS and add a top margin.  Or you could add a bottom margin to their parent element.

For example:
```html
<main>
  <article>
    <!-- content -->
    <!-- need space here -->
  </article>
  <section>
    <!-- content -->
  </section>
</main>
```

```css
/* Option 1 */
section { margin-top: 1rem; }

/* Option 2 */
article { margin-bottom: 1rem; }
```

**Comment by krishmaj** [comment]
There's no particular pattern or commonality as to where the extra space is needed - I just need to be able to drop in blank lines or some vertical spacing wherever it needs to be to improve the layout of the pages.  I'll keep exploring the options.

**Comment by krishmaj** [comment]
I think it's worth pointing out that `br` and/or `pre` are in fact accepted ways of generating vertical whitespace within pug/Jade templates (which is really what we're doing here), simply because there is no built in way to otherwise do so.  So I don't necessarily agree with the assertion that it's wrong to use them in this specific circumstance.

That said, using `div(style = "margin-bottom: 0.Xcm;")` with an appropriate number in place of `X` looks to solve the issue using your preferred CSS styling?

**Comment by micchickenburger** [comment]
Krish, they are not acceptable ways of adding whitespace, but people do it anyway.  Same goes for adding CSS directly to an HTML element like in your example.

It's all about maintainability.  One day when someone is trying to figure out why there is extra spacing somewhere they will burn time trying to find these things, and will have little confidence in making corrections.  The user experience will also lose consistency, which is really important.

In general there are several big "no-noes" when it comes to writing maintainable markup:
- Style-affecting attributes (e.g. `bgcolor`) should never be used
- The style attribute (e.g. `<article style="...">`) should only be used for dynamic style changes (e.g. animating an element with JavaScript for old browsers) and therefore rarely used
- CSS should not exist at all in an HTML document (or PUG in this case) unless it's a single-file website, in which case all the CSS code should be in a single `<style>` element in the `<head>`
- Tables should only ever be used for displaying tabular data, not for laying out content
- HTML is supposed to markup content, which is why it is a markup language.  That means HTML need to describe content.  If you're in the footer of the page, use `<footer>`.  If this is the main part of the page, use `<main>`.  If this is a navigation element, use `<nav>`.  There are also `header`, `article`, `section`, and `aside`.  `div` is a generic element with no meaning, and therefore requires a `class` attribute to describe it.  For example, `<div class="overlay">`.
- HTML elements should never be used to affect the spacing or general styling of content, only layout and description/markup.  See Mozilla's `<br>` reference for more details:  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

By the way, Mozilla's developer reference (MDN) is the ultimate go-to for all things web dev.  Their explanations and descriptions are tied directly to the W3C web standards.  (Conversely, a popular search result is w3schools.com, which has no affiliation with W3C and sometimes gets important details wrong, though it has been getting better over the years--see http://w3fools.com, which used to catalog all their errors).

**Comment by micchickenburger** [comment]
Regarding CSS itself, use pixel units (px, em, rem) instead of print units (cm, in).  CSS applies to more than just websites 😁

**Comment by krishmaj** [comment]
I did specifically say "accepted", not "acceptable"!  And fair enough, yes - pixel units.

To be frank, at this point I don't think I'm ever going to find something that will work for you on my own - and that's nothing against you or your explanations.  It's simply that I honestly don't see what the big deal about this issue is in our context right here, so I'm really struggling to care about solving it.
It might honestly just be better if you figured out how you want to handle the whitespace stuff yourself, and as long as it keeps the actual layouts the same and doesn't involve rewriting the entire set of pug templates, I'll probably be fine with it.

**Comment by krishmaj** [comment]
Also see: https://github.com/DUNE/dunedb/pull/11#discussion_r777070325

**Comment by krishmaj** [comment]
Okay, so at the risk of once again showing how poor my understanding of acceptable styling is ... what about the following change in the `.pug` file:

```
pre #{''}
pre #{''}

img.avatar_image.border(src = userProfile.picture)

pre #{''}

dl
  dt Display Name
```

becomes:

```
div.vert-space-x2
    img.avatar_image.border(src = userProfile.picture)

div.vert-space-x1
    dl
        dt Display Name
```

with the following added to the `main.css` file:

```
.vert-space-x1 {
    margin-top: 1em
}

.vert-space-x2 {
    margin-top: 2em
}
```

**Comment by micchickenburger** [comment]
Yes!  That’s perfect.  There are UI libraries out there like Bootstrap (made by Twitter) and Material (made by Google) that pre-create these classes for you so that you can prototype rapidly, so it’s great to see that you came up with the same approach to this problem as did the experts.  :)
